/**
 * Employee Report PDF Document
 * Generates a PDF report for quarterly/yearly employee reviews
 */
import { Document, Page, Text, View } from '@react-pdf/renderer';
import { EmployeeReport } from '@/hooks/useReports';
import { 
  pdfStyles, 
  formatPdfDateRange,
  BulletList, 
  MetricRow
} from './pdfUtils';

interface Employee {
  id: string;
  name: string;
  email?: string;
  role?: string;
}

interface EmployeeReportPDFProps {
  report: EmployeeReport;
  employee: Employee;
}

export function EmployeeReportPDF({ report, employee }: EmployeeReportPDFProps) {
  const periodLabel = report.reportType === 'quarterly' ? 'Quarterly' : 'Yearly';
  const completionRate = report.actionsCreated > 0
    ? Math.round((report.actionsCompleted / report.actionsCreated) * 100)
    : 0;

  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        {/* Header */}
        <View style={pdfStyles.header}>
          <Text style={pdfStyles.title}>{periodLabel} Performance Report</Text>
          <Text style={pdfStyles.subtitle}>
            {employee.name} • {formatPdfDateRange(report.periodStart, report.periodEnd)}
          </Text>
        </View>

        {/* Employee Info */}
        <View style={pdfStyles.section}>
          <Text style={pdfStyles.sectionTitle}>👤 Employee Information</Text>
          <MetricRow label="Name" value={employee.name} />
          {employee.role && <MetricRow label="Role" value={employee.role} />}
          {employee.email && <MetricRow label="Email" value={employee.email} />}
        </View>

        {/* Key Metrics */}
        <View style={pdfStyles.section}>
          <Text style={pdfStyles.sectionTitle}>📊 Performance Metrics</Text>
          <View style={pdfStyles.statGrid}>
            <View style={pdfStyles.statBox}>
              <Text style={pdfStyles.statValue}>{report.meetingsHeld}</Text>
              <Text style={pdfStyles.statLabel}>Meetings</Text>
            </View>
            <View style={pdfStyles.statBox}>
              <Text style={pdfStyles.statValue}>{report.oneOnOnesCount}</Text>
              <Text style={pdfStyles.statLabel}>1:1s</Text>
            </View>
            <View style={pdfStyles.statBox}>
              <Text style={pdfStyles.statValue}>{report.actionsCompleted}/{report.actionsCreated}</Text>
              <Text style={pdfStyles.statLabel}>Actions ({completionRate}%)</Text>
            </View>
            <View style={pdfStyles.statBox}>
              <Text style={pdfStyles.statValue}>{report.notesCount}</Text>
              <Text style={pdfStyles.statLabel}>Notes</Text>
            </View>
          </View>
        </View>

        {/* Key Accomplishments */}
        {report.keyAccomplishments && report.keyAccomplishments.length > 0 && (
          <View style={pdfStyles.section}>
            <Text style={pdfStyles.sectionTitle}>🎯 Key Accomplishments</Text>
            <BulletList items={report.keyAccomplishments} />
          </View>
        )}

        {/* Development Areas */}
        {report.developmentAreas && report.developmentAreas.length > 0 && (
          <View style={pdfStyles.section}>
            <Text style={pdfStyles.sectionTitle}>📈 Development Areas</Text>
            <BulletList items={report.developmentAreas} />
          </View>
        )}

        {/* Notes */}
        {report.notes && (
          <View style={pdfStyles.section}>
            <Text style={pdfStyles.sectionTitle}>📝 Notes</Text>
            <Text style={pdfStyles.text}>{report.notes}</Text>
          </View>
        )}

        {/* Footer */}
        <View style={pdfStyles.footer}>
          <Text>Generated by Athena • {new Date(report.generatedAt).toLocaleDateString()}</Text>
        </View>
      </Page>
    </Document>
  );
}
