/**
 * Weekly Report PDF Document
 * Generates a PDF report for weekly review
 */
import { Document, Page, Text, View } from '@react-pdf/renderer';
import { WeeklyReport } from '@/hooks/useReports';
import { 
  pdfStyles, 
  formatPdfDateRange, 
  BulletList, 
  MetricRow
} from './pdfUtils';

interface WeeklyReportPDFProps {
  report: WeeklyReport;
  userName: string;
}

export function WeeklyReportPDF({ report, userName }: WeeklyReportPDFProps) {  
  const completionRate = report.actionsCreated > 0
    ? Math.round((report.actionsCompleted / report.actionsCreated) * 100)
    : 0;

  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        {/* Header */}
        <View style={pdfStyles.header}>
          <Text style={pdfStyles.title}>Weekly Review Report</Text>
          <Text style={pdfStyles.subtitle}>
            {formatPdfDateRange(report.weekStart, report.weekEnd)} • {userName}
          </Text>
        </View>

        {/* AI Summary */}
        {report.summary && (
          <View style={pdfStyles.section}>
            <Text style={pdfStyles.sectionTitle}>📊 Summary</Text>
            <Text style={pdfStyles.text}>{report.summary}</Text>
          </View>
        )}

        {/* Key Metrics */}
        <View style={pdfStyles.section}>
          <Text style={pdfStyles.sectionTitle}>📈 Key Metrics</Text>
          <View style={pdfStyles.statGrid}>
            <View style={pdfStyles.statBox}>
              <Text style={pdfStyles.statValue}>{report.meetingHours.toFixed(1)}h</Text>
              <Text style={pdfStyles.statLabel}>Meeting Hours</Text>
            </View>
            <View style={pdfStyles.statBox}>
              <Text style={pdfStyles.statValue}>{report.focusHours.toFixed(1)}h</Text>
              <Text style={pdfStyles.statLabel}>Focus Time</Text>
            </View>
            <View style={pdfStyles.statBox}>
              <Text style={pdfStyles.statValue}>{report.actionsCompleted}/{report.actionsCreated}</Text>
              <Text style={pdfStyles.statLabel}>Actions ({completionRate}%)</Text>
            </View>
            <View style={pdfStyles.statBox}>
              <Text style={pdfStyles.statValue}>{report.decisionsCount}</Text>
              <Text style={pdfStyles.statLabel}>Decisions</Text>
            </View>
          </View>
        </View>

        {/* Top Accomplishments */}
        {report.topAccomplishments && report.topAccomplishments.length > 0 && (
          <View style={pdfStyles.section}>
            <Text style={pdfStyles.sectionTitle}>🎯 Top Accomplishments</Text>
            <BulletList items={report.topAccomplishments.map(a => a.title)} />
          </View>
        )}

        {/* Breakdown by Work Area */}
        {report.breakdownByArea && report.breakdownByArea.length > 0 && (
          <View style={pdfStyles.section}>
            <Text style={pdfStyles.sectionTitle}>📁 Time by Work Area</Text>
            {report.breakdownByArea.map(area => (
              <MetricRow 
                key={area.areaId}
                label={area.areaName}
                value={`${area.hours.toFixed(1)}h (${area.percentage}%)`}
              />
            ))}
          </View>
        )}

        {/* Breakdown by Team */}
        {report.breakdownByTeam && report.breakdownByTeam.length > 0 && (
          <View style={pdfStyles.section}>
            <Text style={pdfStyles.sectionTitle}>👥 Time by Team</Text>
            {report.breakdownByTeam.map(team => (
              <MetricRow 
                key={team.teamId}
                label={team.teamName}
                value={`${team.hours.toFixed(1)}h (${team.percentage}%)`}
              />
            ))}
          </View>
        )}

        {/* Highlights */}
        {report.highlights && report.highlights.length > 0 && (
          <View style={pdfStyles.section}>
            <Text style={pdfStyles.sectionTitle}>✨ Highlights</Text>
            <BulletList items={report.highlights} />
          </View>
        )}

        {/* Recommendations */}
        {report.recommendations && report.recommendations.length > 0 && (
          <View style={pdfStyles.section}>
            <Text style={pdfStyles.sectionTitle}>💡 Recommendations</Text>
            <BulletList items={report.recommendations} />
          </View>
        )}

        {/* Footer */}
        <View style={pdfStyles.footer}>
          <Text>Generated by Athena • {new Date().toLocaleDateString()}</Text>
        </View>
      </Page>
    </Document>
  );
}
